lead_data_collection:
  description: >
    Collect and analyze the following information about the lead:

    - Personal Information:
      - Name: Obtain the full name of the lead.
      - Job Title: Determine the lead's current job title.
      - Role Relevance: Assess how relevant the lead's role is to the decision-making process on a scale from 0 to 10.
      - Professional Background: Optionally, gather a brief description of the lead's professional background.

    - Company Information:
      - Company Name: Identify the name of the company the lead works for.
      - Industry: Determine the industry in which the company operates.
      - Company Size: Estimate the size of the company in terms of employee count.
      - Revenue: If available, collect information on the annual revenue of the company.
      - Market Presence: Evaluate the company's market presence on a scale from 0 to 10.

    - Our Company and Product:
      - Company Name: Sensai Consulting
      - Product: Multi-Agent Consulting Agency
      - ICP: Enterprise companies looking into Agentic automation.
      - Pitch: We are a company that creates AI Agents for automations to any vertical.

    -Lead Data:
      {lead_data}
  expected_output: >
    A comprehensive data report including:
    - Personal information (name, job title, role relevance, and optionally, professional background).
    - Company information (company name, industry, company size, revenue if available, and market presence).

cultural_fit_analysis:
  description: >
    Assess the cultural alignment between the lead's company and our organization by considering the following:
      - Cultural Values: Analyze the company's publicly stated values and internal culture (e.g., innovation, sustainability, employee engagement).
      - Strategic Alignment: Evaluate how well the company's goals and mission align with our organization's strategic objectives.
      - Qualitative Scoring: Assign a qualitative score (0-10) representing the overall cultural fit.
      - Comments: Provide additional comments or observations that support the cultural fit score.

    - Our Company and Product:
      - Company Name: Sensai Consulting
      - Product: Multi-Agent Consulting Agency
      - ICP: Enterprise companies looking into Agentic automation.
      - Pitch: We are a company that creates AI Agents for automations to any vertical.

    - Lead Data:
      {lead_data}
  expected_output: >
    A detailed assessment report including:
    - Cultural fit score (0-10) based on the alignment of values and strategic objectives.
    - Supporting analysis and comments providing context for the cultural fit score.

lead_scoring_and_validation:
  description: >
    Aggregate the collected data and perform the following steps:
    - Score Calculation: Based on predefined criteria, calculate a final lead score (0-100). Consider factors such as:
      - Role Relevance
      - Company Size
      - Market Presence
      - Cultural Fit
    - Scoring Criteria Documentation: List the criteria used to determine the score.
    - Validation: Review the collected data and the calculated score for consistency and accuracy. Make adjustments if necessary.
    - Final Report: Compile a summary report that includes the final validated lead score, the criteria used, and any validation notes.

    - Our Company and Product:
      - Company Name: Sensai Consulting
      - Product: Multi-Agent Consulting Agency
      - ICP: Enterprise companies looking into Agentic automation.
      - Pitch: We are a company that creates AI Agents for automations to any vertical.

    - Lead Data:
      {lead_data}
  expected_output: >
    A validated lead score report including:
    - Final lead score (0-100) with scoring criteria.
    - A summary report detailing the scoring process, criteria used, and validation notes.

email_drafting:
  description: >
    Craft a highly personalized email using the lead's name, job title,
    company information, and any relevant personal or company achievements.
    The email should speak directly to the lead's interests and the needs
    of their company.
    This is not as cold outreach as it is a follow up to a lead form, so
    keep it short and to the point.
    Don't use any salutations or closing remarks, nor too complex sentences.

    Our Company and Product:
      - Company Name: Sensai Consulting
      - Product: Multi-Agent Consulting Agency
      - ICP: Enterprise companies looking into Agentic automation.
      - Pitch: We are a company that creates AI Agents for automations to any vertical.

    Use the following information:
    Personal Info: {personal_info}
    Company Info: {company_info}
    Lead Score: {lead_score}
  expected_output: >
    A personalized email draft that:
    - Addresses the lead by name
    - Acknowledges their role and company
    - Highlights how CrewAI can meet their specific needs or interests

engagement_optimization:
  description: >
    Review the personalized email draft and optimize it with strong CTAs
    and engagement hooks.
    Keep in mind they reached out and filled a lead form.
    Keep it short and to the point.
    Don't use any salutations or closing remarks, nor too complex sentences.
    Ensure the email encourages the lead to schedule a meeting or take
    another desired action immediately.

    Our Company and Product:
      - Company Name: Sensai Consulting
      - Product: Multi-Agent Consulting Agency
      - ICP: Enterprise companies looking into Agentic automation.
      - Pitch: We are a company that creates AI Agents for automations to any vertical.
  expected_output: >
    An optimized email ready for sending, complete with:
    - Strong CTAs
    - Strategically placed engagement hooks that encourage immediate action

database_query:
  description: >
    Answer the following questions about the database: {question}.
  expected_output: >
    You are to run the result of the operation you answered and return the results.