MODEL="gpt-4o-mini"
OPENAI_API_KEY="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"
SERPER_API_KEY = "f62de5bf3120f05e70a0c17f19dfdf92e4dd13ef"
SUPERBASE_URL = "https://xkalsczgvjenrsglkktj.supabase.co"
SUPERBASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrYWxzY3pndmplbnJzZ2xra3RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3NjA3ODYsImV4cCI6MjA1MzMzNjc4Nn0.oWSY4BOfssOU4asQQYPYfU2QljakZoVpLjBKDERgVfY"